version: '3.7'
services:
  app:
    build:
      args:
        user: cristian
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: aurasjobs
    container_name: aurasjobs-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - aurasjobs
  db:
    image: mysql:5.7
    container_name: aurasjobs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - aurasjobs
  nginx:
    image: nginx:1.17-alpine
    container_name: aurasjobs-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - aurasjobs

networks:
  aurasjobs:
    driver: bridge
