<head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5FXJFLK');</script>
    <!-- End Google Tag Manager -->
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "LocalBusiness",
      "name" : "aurasjobs.ro",
      "image" : "https://www.aurasjobs.ro/img/logo995x475.jpg",
      "telephone" : "0725 085 231",
      "email" : "office@aurasjobs.ro",
      "address" : {
        "@type" : "PostalAddress",
        "streetAddress" : "Stefan cel mare nr. 56",
        "addressLocality" : "Constanta",
        "addressCountry" : "Romania",
        "postalCode" : "900683"
      },
      "sameAs" : [
       "https://www.facebook.com/aurasjobs.ro/"
      ],
      "openingHoursSpecification" : {
        "@type" : "OpeningHoursSpecification",
        "dayOfWeek" : {
          "@type" : "DayOfWeek",
          "name" : "10-18"
        }
      },
      "url" : "https://www.aurasjobs.ro",
      "review" : {
        "@type" : "Review",
        "author" : {
          "@type" : "Person",
          "name" : "https://www.facebook.com/aurasjobs.ro"
        }
      }
    }
    </script>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="format-detection" content="telephone=no" />
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/><![endif]-->
    <!--[if lt IE 9]><script src="//ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script><![endif]-->
    <meta name="description" content="Locuri de munca vase de croaziera ocean, rauri, strainatate, restaurant, hotel, punte, bucatari, ospatari, barmani, cameristi, spalatori de vase fara comision." />
    <meta name="keywords" content="locuri de munca, croaziera, fara experienta, vase, joburi, jobs, cruise, nave, angajare, marinar, cadet, masinist, timonier, cadet, ospatar, waiter, waitress, bucatar, sous, chef" />
    <meta property="og:title" content="Locuri de munca / Joburi / Angajari vase de croaziera fara comision" />
    <meta property="og:site_name" content="Locuri de munca / Joburi / Angajari vase de croaziera fara comision" />
    <meta property="og:url" content="https://www.aurasjobs.ro/" />
    <meta property="og:description" content="Locuri de munca vase de croaziera ocean, rauri, strainatate, restaurant, hotel, punte, bucatari, ospatari, barmani, cameristi, spalatori de vase fara comision." />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="https://www.aurasjobs.ro/favicon.png" />
    <meta property="og:image:width" content="300" />
    <meta property="og:image:height" content="300" />
    <meta property="og:locale" content="ro_RO" />
    <meta property="twitter:card" content="summary" />
    <meta property="twitter:title" content="Locuri de munca / Joburi / Angajari vase de croaziera fara comision" />
    <meta property="twitter:description" content="Locuri de munca vase de croaziera ocean, rauri, strainatate, restaurant, hotel, punte, bucatari, ospatari, barmani, cameristi, spalatori de vase fara comision." />
    <meta property="twitter:image" content="https://www.aurasjobs.ro/favicon.png" />
    <meta property="twitter:image:width" content="300" />
    <meta property="twitter:image:height" content="300" />
    <meta name="twitter:card" content="product" />
    <meta name="twitter:description" content="Locuri de munca vase de croaziera ocean, rauri, strainatate, restaurant, hotel, punte, bucatari, ospatari, barmani, cameristi, spalatori de vase fara comision."/>
    <meta name="twitter:title" content="Locuri de munca / Joburi / Angajari vase de croaziera fara comision" />
    <meta name="twitter:site" content="@aurasjobs" />
    <meta name="twitter:domain" content="aurasjobs.ro" />
    <meta name="twitter:image:src" content="https://www.aurasjobs.ro/favicon.png" />
    <meta name="twitter:creator" content="@aurasjobs" />
    <meta name="twitter:label1" content="Jobs" />
    <meta name="twitter:data1" content="Locuri de munca" />
    <meta name="twitter:data2" content="Vase de croaziera" />
    <meta name="twitter:data3" content="Strainatate" />
    <meta name="dc.language" content="RO" />
    <meta name="dc.source" content="https://www.aurasjobs.ro/" />
    <meta name="dc.relation" content="https://www.aurasjobs.ro/" />
    <meta name="dc.title" content="Locuri de munca / Joburi / Angajari vase de croaziera fara comision" />
    <meta name="dc.keywords" content="locuri de munca, croaziera, fara experienta, vase, joburi, jobs, cruise, nave, angajare, marinar, cadet, masinist, timonier, cadet, ospatar, waiter, waitress, bucatar, sous, chef" />
    <meta name="dc.subject" content="Locuri de munca / Joburi / Angajari vase de croaziera fara comision" />
    <meta name="dc.coverage" content="World" />
    <meta name="dc.description" content="Locuri de munca vase de croaziera ocean, rauri, strainatate, restaurant, hotel, punte, bucatari, ospatari, barmani, cameristi, spalatori de vase fara comision." />
    <meta name="dc.format" content="text/html" />
    <meta name="dc.identifier" content="https://www.aurasjobs.ro/" />
    <meta name="DC.creator" content="cristian.devmm.net" />
    <meta name="dc.publisher" content="cristian.devmm.net" />
    <meta name="dc.type" content="Text/Image" />
    <meta name="generator" content="adydevmedia.com" />
    <meta name="author" content="cristian.devmm.net" />
    <meta name="google-site-verification" content="aKuzYBGPI0pg8QwAKodx4Kcaa7PIrkCFwUvwbpXEFSU" />
    <meta name="msvalidate.01" content="05A879D060738F71B036D971F5E9E022" />
    <meta name="wot-verification" content="0ca07c9d96b21ecf1385"/>
    <meta name="norton-safeweb-site-verification" content="fgs92yqqlqwz1bmc798ivrnclsl00bswxy8nygblx-zwvw6j2f17hbaio3k4b7o04qm73wls8h4e3x8ig24aydmrb-pch30q0jx6vlfq44s2lat3yy--i-tpjdulpitu" />
    <meta name="DC.title" content="Locuri de munca / Joburi / Angajari vase de croaziera fara comision" />
    <meta name="geo.region" content="RO-CT" />
    <meta name="geo.placename" content="Constanta" />
    <meta name="geo.position" content="44.197099;28.631725" />
    <meta name="ICBM" content="44.197099, 28.631725" />
    <meta name="robots" content="index, follow" />
    <meta name="revisit-after" content="1 day" />
    <meta name="language" content="ro" />
    <meta name="designer" content="cristian.devmm.net" />
    <meta name="abstract" content="Locuri de munca vase de croaziera" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" type="image/png" href="favicon.png" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="alternate" hreflang="en" href="https://www.aurasjobs.ro/?lang=en" />
    <link rel="alternate" hreflang="ro" href="https://www.aurasjobs.ro" />
    <title>Locuri de munca / Joburi / Angajari vase de croaziera fara comision</title>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Kaushan+Script|Droid+Serif:400,700,400italic,700italic|Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css">

    <!-- Custom styles for this theme -->
    <link href="/public/css/agency.css" rel="stylesheet">

    <!-- Temporary navbar container fix until Bootstrap 4 is patched -->
    <style>.navbar-toggler{z-index:1}@media (max-width:576px){nav>.container{width:100%}}</style>
</head>
